### ISSUE TITLE
Fix code scanning alert - Prototype-polluting function

### ISSUE THREAD

**Issue by p14c31355** [MathExpansion/MathExpansion#133]
Tracking issue for:
- [x] https://github.com/MathExpansion/MathExpansion/security/code-scanning/1

 ## これ誰か治し方教えて……

**Comment by quantumshiro** [comment]
Matrix.tsのコードを見直す必要があるようです。詳細は[Prototype-polluting function](https://github.com/MathExpansion/MathExpansion/security/code-scanning/1)の通りです

**Comment by p14c31355** [comment]
一旦コメントアウトで逃げさせて……
