### ISSUE TITLE
gts の導入

### ISSUE THREAD

**Issue by p14c31355** [MathExpansion/MathExpansion#142]
TypeScript の linter & formatter として良さげなやつが上がってきてたので、要検討ですが……。
モダンなスタックでやっていきたいので何卒検討よろしくお願いします。

**Comment by huequica** [comment]
現状見る限り gts については見送ったほうがいいのではないかと思っています。
というのも、まず命名規則の明文化とそれへの対応、ESLint のルールの拡充などステップを踏んで質を上げていかないと何から手を付ければいいのかわからなくなる恐れがあるからです。
現状は

0. バグ消し
1. 型エラーを消す
2. any の排除
3. できる限りの共通化
4. テストコードの記述やESLint の拡充などで質を上げていく

というロードマップを考えているので、4のステージになったら改めて考えるべきかと。
もっと言えば gts 自体が Prettier と ESLint の wrapper なのでそこまで入れる必要もあるかと言われると微妙な気がしています…

**Comment by p14c31355** [comment]
検討ありがとうございます．
確かに踏むべきステップを踏めていない感じはありますね．
TS な以上 2 番までは確実にやっていき，共通化とテスト，linter のルール拡充等やるべきことはまだありました．

**Comment by p14c31355** [comment]
今気にすることではないので Close

**Comment by p14c31355** [comment]
本当は Oxlint とかもﾁｮｯﾄ気になってる……
