### ISSUE TITLE
開発環境へのエラーチェック追記

### ISSUE THREAD

**Issue by p14c31355** [MathExpansion/MathExpansion#92]
一応セルフチェックの手法として、  
`npx tsc` コマンドでtsのコンパイルができるので、エラーの確認ができます
![image](https://github.com/MathExpansion/MathExpansion/assets/120539864/7d0287d0-1b0c-4870-8a2f-4f8998f6bcad)

_Originally posted by @takahiro1019 in https://github.com/MathExpansion/MathExpansion/issues/91#issuecomment-1798293513_

**Comment by huequica** [comment]
もっと言うと `tsc --noEmit` でファイルチェックのみ実施することができます(CI とかでよく使う)
これを package.json の scripts に追記するのがよさそう。
アサインしてくれれば勝手にやっておきます

**Comment by p14c31355** [comment]
助かります、ありがとうございます

**Comment by p14c31355** [comment]
#96 で解決したので Close
